### ISSUE TITLE
Testing passing a parameter

### ISSUE THREAD

**Issue by cbfn** [camposleite/mobxtesting#6]
Hi! Thanks for sharing this repository and the article. I new in mobx testing. How can I test passing an id into GetAlbuns({id}). Thanks

**Comment by camposleite** [comment]
Hi! Sorry for the delay,

Thanks for you feedback.
I've been working on different type projects for a while but I added an example to hoping to help you.

**Comment by cbfn** [comment]
Thank you very much @camposleite I really appreciate!
